FILES = {'docs/AGENT_FORGE.md': '# Agent Forge\n'
                        '\n'
                        'Need -> capability audit -> blueprint -> implementation -> sandbox -> eval -> security\n'
                        'review -> approval -> limited activation -> observation -> promotion or archive.\n',
 'docs/ARCHITECTURE.md': '# Architecture\n'
                         '\n'
                         'Cano -> API/UI -> Conductor -> Task Store -> Policy/Budget/Router -> team agent -> runtime.\n'
                         'Claude Code and Codex are supervised executors in isolated worktrees. Nexus supplies\n'
                         'small context packs. Forge creates candidate capabilities. Factory V5 and Command\n'
                         'Center remain external integrations. Sensitive actions stop at Approval Gate.\n',
 'docs/CONTENT_OS.md': '# Content OS\n'
                       '\n'
                       'Radar -> verification -> opportunity score -> brief -> script -> storyboard -> Factory\n'
                       'V5 preview -> QA -> approval -> publication -> metrics -> learning. Publication stays blocked '
                       'by default.\n',
 'docs/ENGINEERING_RUNTIME.md': '# Engineering Runtime\n'
                                '\n'
                                'Claude Code plans and reviews. Codex implements and tests. Each task receives an\n'
                                'isolated worktree, timeout, path policy, cost budget, acceptance commands and '
                                'rollback.\n'
                                'Host CLIs may use OAuth subscriptions; APIs are fallbacks for unattended work.\n',
 'docs/NEXUS.md': '# Nexus\n'
                  '\n'
                  'Markdown/Obsidian is the human-readable canonical layer. Graphify is a structural\n'
                  'adapter, not the sole memory. Context Builder returns only relevant notes, decisions,\n'
                  'relationships, failures and permissions. Memory writes are proposed then reviewed.\n',
 'docs/UBUNTU_DEPLOYMENT.md': '# Ubuntu Deployment\n'
                              '\n'
                              'Use Ubuntu 24.04 LTS bare metal with a lightweight desktop when desired. Run Hermes\n'
                              'headless under systemd. Use Docker rootless for untrusted workers; never expose the '
                              'Docker socket.\n',
 'infrastructure/systemd/cano-hermes.service': '[Unit]\n'
                                               'Description=Cano Hermes Agentic OS\n'
                                               'After=network-online.target\n'
                                               '[Service]\n'
                                               'Type=simple\n'
                                               'User=hermes\n'
                                               'WorkingDirectory=/srv/cano-hermes-agentic-os\n'
                                               'Environment=HERMES_DATA_DIR=/var/lib/cano-hermes\n'
                                               'Environment=HERMES_DRY_RUN=true\n'
                                               'ExecStart=/srv/cano-hermes-agentic-os/.venv/bin/cano-hermes serve '
                                               '--host 127.0.0.1 --port 8080\n'
                                               'Restart=on-failure\n'
                                               'NoNewPrivileges=true\n'
                                               'PrivateTmp=true\n'
                                               'ProtectSystem=strict\n'
                                               'ReadWritePaths=/var/lib/cano-hermes\n'
                                               '[Install]\n'
                                               'WantedBy=multi-user.target\n',
 'pyproject.toml': '[build-system]\n'
                   'requires = ["setuptools>=69", "wheel"]\n'
                   'build-backend = "setuptools.build_meta"\n'
                   '\n'
                   '[project]\n'
                   'name = "cano-hermes-agentic-os"\n'
                   'version = "0.2.0"\n'
                   'description = "Autonomous agentic operating system for Cano"\n'
                   'requires-python = ">=3.11"\n'
                   'dependencies = ["fastapi>=0.115", "uvicorn>=0.30", "pydantic>=2.8", "PyYAML>=6.0"]\n'
                   '\n'
                   '[project.optional-dependencies]\n'
                   'dev = ["pytest>=8", "httpx>=0.27", "ruff>=0.6"]\n'
                   '\n'
                   '[project.scripts]\n'
                   'cano-hermes = "cano_hermes.cli:main"\n'
                   '\n'
                   '[tool.setuptools]\n'
                   'package-dir = {"" = "src"}\n'
                   'include-package-data = true\n'
                   '\n'
                   '[tool.setuptools.packages.find]\n'
                   'where = ["src"]\n'
                   '\n'
                   '[tool.setuptools.package-data]\n'
                   'cano_hermes = ["static/*"]\n'
                   '\n'
                   '[tool.pytest.ini_options]\n'
                   'pythonpath = ["src"]\n'
                   '\n'
                   '[tool.ruff]\n'
                   'line-length = 100\n'
                   'target-version = "py311"\n',
 'scripts/demo.py': 'from pathlib import Path\n'
                    'from cano_hermes.config import get_settings\n'
                    'from cano_hermes.conductor import Conductor\n'
                    'from cano_hermes.models import TaskCreate\n'
                    'from cano_hermes.policy import PolicyEngine\n'
                    'from cano_hermes.registry import CapabilityRegistry\n'
                    'from cano_hermes.router import ModelRouter\n'
                    'from cano_hermes.store import SQLiteStore\n'
                    "s=get_settings(); store=SQLiteStore(':memory:'); "
                    'registry=CapabilityRegistry(s.agents_dir,s.skills_dir)\n'
                    'c=Conductor(store,registry,ModelRouter(),PolicyEngine(),Path.cwd(),True)\n'
                    "t=c.plan(TaskCreate(title='Hermes demo',objective='Build and test an API agent'))\n"
                    'print(c.run(t.id))\n',
 'scripts/install_ubuntu.sh': '#!/usr/bin/env bash\n'
                              'set -euo pipefail\n'
                              'sudo apt update\n'
                              'sudo apt install -y python3-venv git docker.io docker-compose-plugin\n'
                              'python3 -m venv .venv\n'
                              '. .venv/bin/activate\n'
                              "pip install -e '.[dev]'\n"
                              'python scripts/validate.py\n'
                              'pytest -q\n'
                              "printf 'Run: source .venv/bin/activate && cano-hermes serve --host 0.0.0.0\n"
                              "'\n"}
