FILES = {'src/cano_hermes/conductor.py': 'from __future__ import annotations\n'
                                 'from pathlib import Path\n'
                                 'from .models import TaskCreate, TaskRecord, TaskStatus\n'
                                 'from .policy import PolicyEngine\n'
                                 'from .registry import CapabilityRegistry\n'
                                 'from .router import ModelRouter\n'
                                 'from .runtimes import EXECUTORS, RuntimeRequest\n'
                                 'from .store import SQLiteStore\n'
                                 '\n'
                                 '\n'
                                 'KEYWORDS = {\n'
                                 '    "engineering": {"code", "repo", "system", "api", "agent", "build", "debug", '
                                 '"claude", "codex"},\n'
                                 '    "research": {"research", "investigate", "sources", "report", "documents"},\n'
                                 '    "trends": {"trend", "news", "viral", "competitor", "current"},\n'
                                 '    "content": {"content", "reel", "script", "storyboard", "channel", "video"},\n'
                                 '    "operations": {"server", "docker", "deploy", "automation", "whatsapp", '
                                 '"voice"},\n'
                                 '}\n'
                                 'TEAM_MAP = {"engineering": "engineering", "research": "research", "trends": '
                                 '"research",\n'
                                 '            "content": "content", "operations": "operations", "general": '
                                 '"governance"}\n'
                                 '\n'
                                 '\n'
                                 'class Conductor:\n'
                                 '    def __init__(self, store: SQLiteStore, registry: CapabilityRegistry,\n'
                                 '                 router: ModelRouter, policy: PolicyEngine, workspace: Path, '
                                 'dry_run: bool = True):\n'
                                 '        self.store, self.registry, self.router, self.policy = store, registry, '
                                 'router, policy\n'
                                 '        self.workspace, self.dry_run = workspace, dry_run\n'
                                 '\n'
                                 '    def classify(self, text: str) -> str:\n'
                                 '        words = set(text.lower().replace("/", " ").split())\n'
                                 '        scores = {domain: len(words & keys) for domain, keys in KEYWORDS.items()}\n'
                                 '        domain, score = max(scores.items(), key=lambda item: item[1])\n'
                                 '        return domain if score else "general"\n'
                                 '\n'
                                 '    def plan(self, data: TaskCreate) -> TaskRecord:\n'
                                 '        domain = data.domain or self.classify(f"{data.title} {data.objective}")\n'
                                 '        task = self.store.create_task(data.model_copy(update={"domain": domain}))\n'
                                 '        agent = self.registry.choose_agent(TEAM_MAP.get(domain, "governance"))\n'
                                 '        route = self.router.route(task, "plan" if domain == "engineering" else '
                                 '"execute")\n'
                                 '        task = self.store.update_task(task.id, status=TaskStatus.PLANNED,\n'
                                 '            assigned_agent=agent["id"], route=route.model_dump())\n'
                                 '        self.store.add_event(task.id, "task.planned", {"agent": agent["id"], '
                                 '"route": route.model_dump()})\n'
                                 '        return task\n'
                                 '\n'
                                 '    def run(self, task_id: str):\n'
                                 '        task = self.store.get_task(task_id)\n'
                                 '        if task is None:\n'
                                 '            raise KeyError(task_id)\n'
                                 '        decision = self.policy.decide("workspace_write", task.risk)\n'
                                 '        if not decision.allowed or decision.approval_required:\n'
                                 '            status = TaskStatus.BLOCKED if not decision.allowed else '
                                 'TaskStatus.REVIEW\n'
                                 '            self.store.update_task(task.id, status=status)\n'
                                 '            self.store.add_event(task.id, "execution.gated", {"reason": '
                                 'decision.reason})\n'
                                 '            return {"task": self.store.get_task(task.id), "policy": '
                                 'decision.__dict__}\n'
                                 '        runtime = (task.route or {}).get("runtime", "hermes")\n'
                                 '        executor = EXECUTORS.get(runtime, EXECUTORS["hermes"])\n'
                                 '        self.store.update_task(task.id, status=TaskStatus.RUNNING)\n'
                                 '        request = RuntimeRequest(task=task, prompt=task.objective, '
                                 'workspace=self.workspace)\n'
                                 '        result = executor.execute(request, dry_run=self.dry_run)\n'
                                 '        self.store.update_task(task.id, status=TaskStatus.REVIEW)\n'
                                 '        self.store.add_event(task.id, "execution.finished", result.model_dump())\n'
                                 '        return {"task": self.store.get_task(task.id), "execution": result}\n'}
