FILES = {'src/cano_hermes/store.py': 'from __future__ import annotations\n'
                             'import json\n'
                             'import sqlite3\n'
                             'from pathlib import Path\n'
                             'from threading import RLock\n'
                             'from typing import Any\n'
                             'from .models import TaskCreate, TaskRecord, TaskStatus, utcnow\n'
                             '\n'
                             '\n'
                             'class SQLiteStore:\n'
                             '    def __init__(self, path: str | Path):\n'
                             '        self.path = str(path)\n'
                             '        if self.path != ":memory:":\n'
                             '            Path(self.path).parent.mkdir(parents=True, exist_ok=True)\n'
                             '        self._lock = RLock()\n'
                             '        self._conn = sqlite3.connect(self.path, check_same_thread=False)\n'
                             '        self._conn.row_factory = sqlite3.Row\n'
                             '        self._conn.execute("PRAGMA journal_mode=WAL")\n'
                             '        self._conn.executescript("""\n'
                             '        CREATE TABLE IF NOT EXISTS tasks(\n'
                             '          id TEXT PRIMARY KEY, title TEXT NOT NULL, objective TEXT NOT NULL,\n'
                             '          domain TEXT, risk TEXT NOT NULL, max_cost_usd REAL NOT NULL,\n'
                             '          metadata TEXT NOT NULL, status TEXT NOT NULL, assigned_agent TEXT,\n'
                             '          route TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL\n'
                             '        );\n'
                             '        CREATE TABLE IF NOT EXISTS events(\n'
                             '          id INTEGER PRIMARY KEY AUTOINCREMENT, task_id TEXT NOT NULL,\n'
                             '          kind TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL\n'
                             '        );\n'
                             '        CREATE TABLE IF NOT EXISTS approvals(\n'
                             '          id INTEGER PRIMARY KEY AUTOINCREMENT, task_id TEXT NOT NULL,\n'
                             '          action TEXT NOT NULL, state TEXT NOT NULL, reason TEXT,\n'
                             '          created_at TEXT NOT NULL, decided_at TEXT\n'
                             '        );\n'
                             '        """)\n'
                             '        self._conn.commit()\n'
                             '\n'
                             '    def create_task(self, data: TaskCreate) -> TaskRecord:\n'
                             '        task = TaskRecord(**data.model_dump())\n'
                             '        with self._lock:\n'
                             '            self._conn.execute(\n'
                             '                "INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",\n'
                             '                (task.id, task.title, task.objective, task.domain, task.risk.value,\n'
                             '                 task.max_cost_usd, json.dumps(task.metadata), task.status.value,\n'
                             '                 task.assigned_agent, None, task.created_at, task.updated_at),\n'
                             '            )\n'
                             '            self._conn.commit()\n'
                             '        self.add_event(task.id, "task.created", {"title": task.title})\n'
                             '        return task\n'
                             '\n'
                             '    def _row(self, row: sqlite3.Row) -> TaskRecord:\n'
                             '        data = dict(row)\n'
                             '        data["metadata"] = json.loads(data["metadata"])\n'
                             '        data["route"] = json.loads(data["route"]) if data["route"] else None\n'
                             '        return TaskRecord(**data)\n'
                             '\n'
                             '    def get_task(self, task_id: str) -> TaskRecord | None:\n'
                             '        row = self._conn.execute("SELECT * FROM tasks WHERE id=?", '
                             '(task_id,)).fetchone()\n'
                             '        return self._row(row) if row else None\n'
                             '\n'
                             '    def list_tasks(self, limit: int = 100) -> list[TaskRecord]:\n'
                             '        rows = self._conn.execute(\n'
                             '            "SELECT * FROM tasks ORDER BY created_at DESC LIMIT ?", (limit,)\n'
                             '        ).fetchall()\n'
                             '        return [self._row(row) for row in rows]\n'
                             '\n'
                             '    def update_task(self, task_id: str, **changes: Any) -> TaskRecord:\n'
                             '        allowed = {"status", "domain", "assigned_agent", "route"}\n'
                             '        fields = {k: v for k, v in changes.items() if k in allowed}\n'
                             '        if not fields:\n'
                             '            current = self.get_task(task_id)\n'
                             '            if current is None:\n'
                             '                raise KeyError(task_id)\n'
                             '            return current\n'
                             '        normalized = {}\n'
                             '        for key, value in fields.items():\n'
                             '            if isinstance(value, TaskStatus):\n'
                             '                value = value.value\n'
                             '            if key == "route" and value is not None:\n'
                             '                value = json.dumps(value)\n'
                             '            normalized[key] = value\n'
                             '        normalized["updated_at"] = utcnow()\n'
                             '        sql = ", ".join(f"{key}=?" for key in normalized)\n'
                             '        with self._lock:\n'
                             '            self._conn.execute(\n'
                             '                f"UPDATE tasks SET {sql} WHERE id=?", (*normalized.values(), task_id)\n'
                             '            )\n'
                             '            self._conn.commit()\n'
                             '        task = self.get_task(task_id)\n'
                             '        if task is None:\n'
                             '            raise KeyError(task_id)\n'
                             '        return task\n'
                             '\n'
                             '    def add_event(self, task_id: str, kind: str, payload: dict[str, Any]) -> None:\n'
                             '        with self._lock:\n'
                             '            self._conn.execute(\n'
                             '                "INSERT INTO events(task_id,kind,payload,created_at) VALUES(?,?,?,?)",\n'
                             '                (task_id, kind, json.dumps(payload), utcnow()),\n'
                             '            )\n'
                             '            self._conn.commit()\n'
                             '\n'
                             '    def list_events(self, task_id: str) -> list[dict[str, Any]]:\n'
                             '        rows = self._conn.execute(\n'
                             '            "SELECT * FROM events WHERE task_id=? ORDER BY id", (task_id,)\n'
                             '        ).fetchall()\n'
                             '        return [{**dict(row), "payload": json.loads(row["payload"])} for row in rows]\n',
 'tests/__init__.py': '',
 'tests/test_api.py': 'from pathlib import Path\n'
                      'from fastapi.testclient import TestClient\n'
                      'from cano_hermes.api import build_app\n'
                      'ROOT=Path(__file__).resolve().parents[1]\n'
                      '\n'
                      'def test_health_and_task(tmp_path):\n'
                      "    client=TestClient(build_app(ROOT,tmp_path/'test.db'))\n"
                      "    health=client.get('/health').json()\n"
                      "    assert health['agents'] >= 38 and health['skills'] >= 40\n"
                      "    created=client.post('/api/tasks',json={'title':'Create agent','objective':'Build and test "
                      "an agent'}).json()\n"
                      "    assert created['assigned_agent']\n"
                      '    run=client.post(f"/api/tasks/{created[\'id\']}/run")\n'
                      '    assert run.status_code == 200\n',
 'tests/test_core.py': 'from pathlib import Path\n'
                       'from cano_hermes.conductor import Conductor\n'
                       'from cano_hermes.models import RiskLevel, TaskCreate, TaskStatus\n'
                       'from cano_hermes.policy import PolicyEngine\n'
                       'from cano_hermes.registry import CapabilityRegistry\n'
                       'from cano_hermes.router import ModelRouter\n'
                       'from cano_hermes.store import SQLiteStore\n'
                       '\n'
                       'ROOT=Path(__file__).resolve().parents[1]\n'
                       '\n'
                       'def conductor():\n'
                       '    return '
                       "Conductor(SQLiteStore(':memory:'),CapabilityRegistry(ROOT/'agents',ROOT/'skills'),ModelRouter(),PolicyEngine(),ROOT,True)\n"
                       '\n'
                       'def test_registry_counts():\n'
                       "    r=CapabilityRegistry(ROOT/'agents',ROOT/'skills')\n"
                       '    assert len(r.agents()) >= 38\n'
                       '    assert len(r.skills()) >= 40\n'
                       '\n'
                       'def test_engineering_routes_to_claude_for_plan():\n'
                       "    c=conductor(); task=c.plan(TaskCreate(title='Build API',objective='Build and test code in "
                       "repo'))\n"
                       "    assert task.domain == 'engineering'\n"
                       "    assert task.route['runtime'] == 'claude-code'\n"
                       '\n'
                       'def test_low_risk_dry_run_reaches_review():\n'
                       "    c=conductor(); task=c.plan(TaskCreate(title='Research task',objective='research documents "
                       "and sources'))\n"
                       '    result=c.run(task.id)\n'
                       "    assert result['task'].status == TaskStatus.REVIEW\n"
                       "    assert result['execution'].dry_run is True\n"
                       '\n'
                       'def test_high_risk_is_gated():\n'
                       "    c=conductor(); task=c.plan(TaskCreate(title='Deploy',objective='deploy "
                       "production',risk=RiskLevel.HIGH))\n"
                       '    result=c.run(task.id)\n'
                       "    assert result['task'].status == TaskStatus.REVIEW\n"
                       "    assert result['policy']['approval_required'] is True\n"
                       '\n'
                       'def test_destructive_action_blocked():\n'
                       "    decision=PolicyEngine().decide('delete_repository')\n"
                       '    assert not decision.allowed\n',
 'vault/01-home/Hermes Home.md': '# Hermes Home\n\nCano Hermes OS coordinates projects, agents, tasks and approvals.\n',
 'vault/04-content/Content Operations.md': '# Content Operations\n'
                                           '\n'
                                           'Radar connects to scripts, storyboards, Factory V5, metrics and '
                                           'learning.\n',
 'vault/05-systems/System Architecture.md': '# System Architecture\n'
                                            '\n'
                                            '[[Hermes Home]] connects Conductor, Router, Registry, Nexus, Forge and '
                                            'external adapters.\n',
 'vault/09-decisions/Autonomy Policy.md': '# Autonomy Policy\n'
                                          '\n'
                                          'Low-risk reversible work may run automatically. Sensitive work requires '
                                          'approval.\n'}
