FILES = {'src/cano_hermes/config.py': 'from __future__ import annotations\n'
                              'import os\n'
                              'from dataclasses import dataclass\n'
                              'from pathlib import Path\n'
                              '\n'
                              '\n'
                              '@dataclass(frozen=True)\n'
                              'class Settings:\n'
                              '    root: Path\n'
                              '    data_dir: Path\n'
                              '    agents_dir: Path\n'
                              '    skills_dir: Path\n'
                              '    vault_dir: Path\n'
                              '    dry_run: bool\n'
                              '    routing_strategy: str\n'
                              '\n'
                              '\n'
                              'def get_settings(root: Path | None = None) -> Settings:\n'
                              '    base = (root or Path.cwd()).resolve()\n'
                              '    data = Path(os.getenv("HERMES_DATA_DIR", base / "runtime"))\n'
                              '    if not data.is_absolute():\n'
                              '        data = base / data\n'
                              '    return Settings(\n'
                              '        root=base,\n'
                              '        data_dir=data,\n'
                              '        agents_dir=base / "agents",\n'
                              '        skills_dir=base / "skills",\n'
                              '        vault_dir=base / "vault",\n'
                              '        dry_run=os.getenv("HERMES_DRY_RUN", "true").lower() != "false",\n'
                              '        routing_strategy=os.getenv("HERMES_ROUTING_STRATEGY", "subscription_first"),\n'
                              '    )\n',
 'src/cano_hermes/forge.py': 'from __future__ import annotations\n'
                             'import json\n'
                             'from pathlib import Path\n'
                             'import yaml\n'
                             '\n'
                             '\n'
                             'class AgentForge:\n'
                             '    def __init__(self, output: Path):\n'
                             '        self.output = output\n'
                             '\n'
                             '    def create_agent(self, agent_id: str, team: str, objective: str) -> Path:\n'
                             '        target = self.output / "agents" / f"{agent_id}.yaml"\n'
                             '        target.parent.mkdir(parents=True, exist_ok=True)\n'
                             '        data = {"id": agent_id, "name": agent_id.replace("-", " ").title(), "team": '
                             'team,\n'
                             '                "role": "worker", "objective": objective, "status": "candidate",\n'
                             '                "runtime": "hermes", "permissions": {"production": "denied"},\n'
                             '                "evaluation": {"required": True, "minimum_score": 0.85}}\n'
                             '        target.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")\n'
                             '        return target\n'
                             '\n'
                             '    def create_skill(self, skill_id: str, purpose: str) -> Path:\n'
                             '        folder = self.output / "skills" / skill_id\n'
                             '        folder.mkdir(parents=True, exist_ok=True)\n'
                             '        manifest = {"id": skill_id, "version": "0.1.0", "status": "candidate", '
                             '"purpose": purpose}\n'
                             '        (folder / "manifest.json").write_text(json.dumps(manifest, indent=2), '
                             'encoding="utf-8")\n'
                             '        (folder / "SKILL.md").write_text(f"# {skill_id}\\n\\n{purpose}\\n", '
                             'encoding="utf-8")\n'
                             '        return folder\n',
 'src/cano_hermes/models.py': 'from __future__ import annotations\n'
                              'from datetime import datetime, timezone\n'
                              'from enum import StrEnum\n'
                              'from typing import Any\n'
                              'from uuid import uuid4\n'
                              'from pydantic import BaseModel, Field\n'
                              '\n'
                              '\n'
                              'def utcnow() -> str:\n'
                              '    return datetime.now(timezone.utc).isoformat()\n'
                              '\n'
                              '\n'
                              'class TaskStatus(StrEnum):\n'
                              '    QUEUED = "queued"\n'
                              '    PLANNED = "planned"\n'
                              '    RUNNING = "running"\n'
                              '    REVIEW = "review"\n'
                              '    DONE = "done"\n'
                              '    BLOCKED = "blocked"\n'
                              '    FAILED = "failed"\n'
                              '\n'
                              '\n'
                              'class RiskLevel(StrEnum):\n'
                              '    LOW = "low"\n'
                              '    MEDIUM = "medium"\n'
                              '    HIGH = "high"\n'
                              '    CRITICAL = "critical"\n'
                              '\n'
                              '\n'
                              'class TaskCreate(BaseModel):\n'
                              '    title: str = Field(min_length=3, max_length=180)\n'
                              '    objective: str = Field(min_length=3, max_length=8000)\n'
                              '    domain: str | None = None\n'
                              '    risk: RiskLevel = RiskLevel.LOW\n'
                              '    max_cost_usd: float = Field(default=0.50, ge=0, le=100)\n'
                              '    metadata: dict[str, Any] = Field(default_factory=dict)\n'
                              '\n'
                              '\n'
                              'class TaskRecord(TaskCreate):\n'
                              '    id: str = Field(default_factory=lambda: f"task-{uuid4().hex[:12]}")\n'
                              '    status: TaskStatus = TaskStatus.QUEUED\n'
                              '    assigned_agent: str | None = None\n'
                              '    route: dict[str, Any] | None = None\n'
                              '    created_at: str = Field(default_factory=utcnow)\n'
                              '    updated_at: str = Field(default_factory=utcnow)\n'
                              '\n'
                              '\n'
                              'class RouteDecision(BaseModel):\n'
                              '    profile: str\n'
                              '    provider: str\n'
                              '    model: str\n'
                              '    runtime: str\n'
                              '    billing: str\n'
                              '    reason: str\n'
                              '    estimated_cost_usd: float = 0.0\n'
                              '\n'
                              '\n'
                              'class ExecutionResult(BaseModel):\n'
                              '    execution_id: str\n'
                              '    task_id: str\n'
                              '    runtime: str\n'
                              '    status: str\n'
                              '    command: list[str] = Field(default_factory=list)\n'
                              '    stdout: str = ""\n'
                              '    stderr: str = ""\n'
                              '    return_code: int | None = None\n'
                              '    dry_run: bool = True\n',
 'src/cano_hermes/nexus.py': 'from __future__ import annotations\n'
                             'import re\n'
                             'from dataclasses import dataclass\n'
                             'from pathlib import Path\n'
                             '\n'
                             'LINK = re.compile(r"\\[\\[([^\\]]+)\\]\\]")\n'
                             '\n'
                             '\n'
                             '@dataclass(frozen=True)\n'
                             'class Note:\n'
                             '    path: str\n'
                             '    title: str\n'
                             '    body: str\n'
                             '    links: tuple[str, ...]\n'
                             '\n'
                             '\n'
                             'class Nexus:\n'
                             '    def __init__(self, vault: Path):\n'
                             '        self.vault = vault\n'
                             '\n'
                             '    def notes(self) -> list[Note]:\n'
                             '        result = []\n'
                             '        if not self.vault.exists():\n'
                             '            return result\n'
                             '        for path in sorted(self.vault.rglob("*.md")):\n'
                             '            body = path.read_text(encoding="utf-8", errors="replace")\n'
                             '            title = next((line[2:].strip() for line in body.splitlines() if '
                             'line.startswith("# ")), path.stem)\n'
                             '            result.append(Note(str(path.relative_to(self.vault)), title, body, '
                             'tuple(LINK.findall(body))))\n'
                             '        return result\n'
                             '\n'
                             '    def search(self, query: str, limit: int = 8) -> list[dict]:\n'
                             '        terms = {term.lower() for term in query.split() if len(term) > 2}\n'
                             '        scored = []\n'
                             '        for note in self.notes():\n'
                             '            haystack = f"{note.title} {note.body}".lower()\n'
                             '            score = sum(haystack.count(term) for term in terms)\n'
                             '            if score:\n'
                             '                scored.append((score, note))\n'
                             '        scored.sort(key=lambda item: (-item[0], item[1].title))\n'
                             '        return [{"path": note.path, "title": note.title, "score": score,\n'
                             '                 "excerpt": note.body[:500]} for score, note in scored[:limit]]\n'
                             '\n'
                             '    def context(self, query: str, limit: int = 5) -> str:\n'
                             '        return "\\n\\n".join(\n'
                             '            f"## {item[\'title\']}\\n{item[\'excerpt\']}" for item in self.search(query, '
                             'limit)\n'
                             '        )\n',
 'src/cano_hermes/policy.py': 'from __future__ import annotations\n'
                              'from dataclasses import dataclass\n'
                              'from .models import RiskLevel\n'
                              '\n'
                              '\n'
                              '@dataclass(frozen=True)\n'
                              'class PolicyDecision:\n'
                              '    allowed: bool\n'
                              '    approval_required: bool\n'
                              '    reason: str\n'
                              '\n'
                              '\n'
                              'BLOCKED = {"delete_repository", "expose_secret", "disable_security", '
                              '"mount_docker_socket"}\n'
                              'SENSITIVE = {"deploy", "publish", "send_message", "spend_money", "merge_main", '
                              '"write_production"}\n'
                              '\n'
                              '\n'
                              'class PolicyEngine:\n'
                              '    def decide(self, action: str, risk: RiskLevel = RiskLevel.LOW) -> PolicyDecision:\n'
                              '        if action in BLOCKED:\n'
                              '            return PolicyDecision(False, True, f"{action} is blocked by policy")\n'
                              '        if action in SENSITIVE or risk in {RiskLevel.HIGH, RiskLevel.CRITICAL}:\n'
                              '            return PolicyDecision(True, True, "explicit human approval required")\n'
                              '        if risk == RiskLevel.MEDIUM:\n'
                              '            return PolicyDecision(True, True, "review before execution")\n'
                              '        return PolicyDecision(True, False, "reversible low-risk action")\n',
 'src/cano_hermes/registry.py': 'from __future__ import annotations\n'
                                'import json\n'
                                'from pathlib import Path\n'
                                'import yaml\n'
                                '\n'
                                '\n'
                                'class CapabilityRegistry:\n'
                                '    def __init__(self, agents_dir: Path, skills_dir: Path):\n'
                                '        self.agents_dir = agents_dir\n'
                                '        self.skills_dir = skills_dir\n'
                                '\n'
                                '    def agents(self) -> list[dict]:\n'
                                '        result = []\n'
                                '        for path in sorted(self.agents_dir.rglob("*.yaml")):\n'
                                '            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}\n'
                                '            data["source_path"] = str(path)\n'
                                '            result.append(data)\n'
                                '        return result\n'
                                '\n'
                                '    def skills(self) -> list[dict]:\n'
                                '        result = []\n'
                                '        for path in sorted(self.skills_dir.rglob("manifest.json")):\n'
                                '            data = json.loads(path.read_text(encoding="utf-8"))\n'
                                '            data["source_path"] = str(path)\n'
                                '            result.append(data)\n'
                                '        return result\n'
                                '\n'
                                '    def find_agent(self, agent_id: str) -> dict | None:\n'
                                '        return next((item for item in self.agents() if item.get("id") == agent_id), '
                                'None)\n'
                                '\n'
                                '    def choose_agent(self, team: str) -> dict:\n'
                                '        agents = [item for item in self.agents() if item.get("team") == team]\n'
                                '        if not agents:\n'
                                '            agents = self.agents()\n'
                                '        if not agents:\n'
                                '            raise RuntimeError("No agents registered")\n'
                                '        leads = [item for item in agents if item.get("role") == "lead"]\n'
                                '        return (leads or agents)[0]\n'}
