FILES = {'src/cano_hermes/cli.py': 'from __future__ import annotations\n'
                           'import argparse\n'
                           'import json\n'
                           'from pathlib import Path\n'
                           'import uvicorn\n'
                           'from .api import build_app\n'
                           'from .config import get_settings\n'
                           'from .conductor import Conductor\n'
                           'from .models import TaskCreate\n'
                           'from .policy import PolicyEngine\n'
                           'from .registry import CapabilityRegistry\n'
                           'from .router import ModelRouter\n'
                           'from .store import SQLiteStore\n'
                           '\n'
                           '\n'
                           'def main() -> None:\n'
                           '    parser = argparse.ArgumentParser(prog="cano-hermes")\n'
                           '    sub = parser.add_subparsers(dest="command", required=True)\n'
                           '    serve = sub.add_parser("serve")\n'
                           '    serve.add_argument("--host", default="127.0.0.1")\n'
                           '    serve.add_argument("--port", type=int, default=8080)\n'
                           '    demo = sub.add_parser("demo")\n'
                           '    demo.add_argument("objective", nargs="?", default="Build and test a safe example '
                           'agent")\n'
                           '    args = parser.parse_args()\n'
                           '    if args.command == "serve":\n'
                           '        uvicorn.run(build_app(), host=args.host, port=args.port)\n'
                           '        return\n'
                           '    settings = get_settings()\n'
                           '    store = SQLiteStore(settings.data_dir / "hermes.db")\n'
                           '    registry = CapabilityRegistry(settings.agents_dir, settings.skills_dir)\n'
                           '    conductor = Conductor(store, registry, ModelRouter(), PolicyEngine(), Path.cwd(), '
                           'True)\n'
                           '    task = conductor.plan(TaskCreate(title="CLI demo", objective=args.objective))\n'
                           '    print(json.dumps(conductor.run(task.id), default=str, indent=2))\n'
                           '\n'
                           '\n'
                           'if __name__ == "__main__":\n'
                           '    main()\n'}
