FILES = {'.env.example': 'HERMES_ENV=development\n'
                 'HERMES_DATA_DIR=runtime\n'
                 'HERMES_DRY_RUN=true\n'
                 'HERMES_ROUTING_STRATEGY=subscription_first\n'
                 'ANTHROPIC_API_KEY=\n'
                 'OPENAI_API_KEY=\n'
                 'MOONSHOT_API_KEY=\n'
                 'DEEPSEEK_API_KEY=\n'
                 'DASHSCOPE_API_KEY=\n'
                 'XAI_API_KEY=\n',
 '.github/workflows/ci.yml': 'name: CI\n'
                             'on: [push, pull_request]\n'
                             'jobs:\n'
                             '  test:\n'
                             '    runs-on: ubuntu-latest\n'
                             '    steps:\n'
                             '      - uses: actions/checkout@v4\n'
                             '      - uses: actions/setup-python@v5\n'
                             '        with: {python-version: "3.12"}\n'
                             "      - run: pip install -e '.[dev]'\n"
                             '      - run: python scripts/validate.py\n'
                             '      - run: python -m compileall -q src scripts tests\n'
                             '      - run: ruff check .\n'
                             '      - run: pytest -q\n',
 '.gitignore': '.env\n'
               '.venv/\n'
               '__pycache__/\n'
               '*.pyc\n'
               '.pytest_cache/\n'
               '.ruff_cache/\n'
               '*.db\n'
               'runtime/\n'
               'generated/\n'
               'artifacts/\n',
 'AGENTS.md': '# Agent Rules\n'
              '\n'
              '- Hermes Conductor coordina; no ejecuta trabajo especializado directamente.\n'
              '- Claude diseña y revisa; Codex implementa y prueba en worktrees separados.\n'
              '- Ningún agente puede aprobar su propia salida.\n'
              '- Producción, publicación, dinero, secretos y acciones destructivas requieren aprobación.\n'
              '- Todo agente nuevo inicia en candidate/quarantine y debe pasar evals.\n'
              '- No se entrega acceso al socket Docker a agentes o contenedores.\n',
 'BUILD_REPORT.md': '# Build Report\n'
                    '\n'
                    'Foundation generated from a transparent bootstrap. Validation requires at least\n'
                    '38 agent manifests, 40 skill manifests, importable Python modules and passing tests.\n',
 'CLAUDE.md': '# Claude Code Instructions\n'
              '\n'
              'Lee AGENTS.md, SECURITY.md y docs/ARCHITECTURE.md antes de modificar código.\n'
              'Trabaja con TDD, diffs pequeños y worktrees. Revisa arquitectura y criterios de\n'
              'aceptación. No rediseñes desde cero ni mezcles Command Center dentro de Hermes.\n',
 'Dockerfile': 'FROM python:3.12-slim\n'
               'WORKDIR /app\n'
               'COPY . .\n'
               'RUN pip install --no-cache-dir .\n'
               'ENV HERMES_DATA_DIR=/data HERMES_DRY_RUN=true\n'
               'EXPOSE 8080\n'
               'CMD ["cano-hermes", "serve", "--host", "0.0.0.0", "--port", "8080"]\n',
 'IMPLEMENTATION_STATUS.md': '# Implementation Status v0.2.0\n'
                             '\n'
                             'Implementado: SQLite, task/event engine, registry, policy engine, budget-aware model\n'
                             'router, dry-run executors, Claude/Codex command builders, Nexus Markdown search,\n'
                             'Agent/Skill Forge, FastAPI, dashboard, Docker, systemd, CI, tests, 38 agents and 40 '
                             'skills.\n'
                             '\n'
                             'Pendiente de entorno: autenticación OAuth, claves reales, Codex App Server protocol,\n'
                             'Graphify real, mensajería, Factory V5 real, producción y pruebas prolongadas en '
                             'Ubuntu.\n',
 'Makefile': '.PHONY: install test validate run\n'
             'install:\n'
             "\tpip install -e '.[dev]'\n"
             'test:\n'
             '\tpytest -q\n'
             'validate:\n'
             '\tpython scripts/validate.py\n'
             'run:\n'
             '\tcano-hermes serve\n',
 'README.md': '# Cano Hermes Agentic OS\n'
              '\n'
              'Foundation funcional para un sistema agéntico autónomo, supervisado y económico.\n'
              'Hermes coordina Claude Code, Codex, APIs económicas, modelos premium, agentes,\n'
              'skills, Nexus, Forge, Radar y sistemas externos sin mezclarse con Command Center.\n'
              '\n'
              '## Arranque\n'
              '\n'
              '```bash\n'
              'python3 -m venv .venv\n'
              'source .venv/bin/activate\n'
              "pip install -e '.[dev]'\n"
              'python scripts/validate.py\n'
              'pytest -q\n'
              'cano-hermes serve\n'
              '```\n'
              '\n'
              'Abre `http://127.0.0.1:8080`.\n'
              '\n'
              'Las ejecuciones reales están bloqueadas por defecto. Configura las CLI, OAuth,\n'
              'claves y políticas únicamente en Ubuntu. Nunca guardes secretos en Git.\n',
 'ROADMAP.md': '# Roadmap\n'
               '\n'
               '1. Foundation: API, UI, tareas, agentes, router, permisos y Nexus.\n'
               '2. Engineering Runtime: Claude Code, Codex App Server, worktrees y artefactos.\n'
               '3. Nexus: Obsidian, Graphify, búsqueda y memoria gobernada.\n'
               '4. Forge: agentes, skills, MCP, contenedores y evaluaciones.\n'
               '5. Content OS: Radar, Factory V5, producción y métricas.\n'
               '6. Comunicaciones y autonomía progresiva.\n',
 'SECURITY.md': '# Security\n'
                '\n'
                '- Secretos fuera del repositorio.\n'
                '- Docker rootless y sin montar `/var/run/docker.sock`.\n'
                '- Comandos por lista permitida, sin `shell=True`.\n'
                '- Red denegada por defecto en sandboxes.\n'
                '- Publicar, desplegar, gastar, enviar mensajes o destruir requiere aprobación explícita.\n'
                '- Los plugins, MCP y agentes importados pasan por cuarentena, auditoría y evals.\n',
 'docker-compose.yml': 'services:\n'
                       '  hermes:\n'
                       '    build: .\n'
                       '    ports: ["8080:8080"]\n'
                       '    environment:\n'
                       '      HERMES_DATA_DIR: /data\n'
                       '      HERMES_DRY_RUN: "true"\n'
                       '    volumes: ["hermes-data:/data"]\n'
                       '    read_only: true\n'
                       '    tmpfs: ["/tmp"]\n'
                       '    security_opt: ["no-new-privileges:true"]\n'
                       'volumes:\n'
                       '  hermes-data: {}\n'}
