FILES = {'src/cano_hermes/router.py': 'from __future__ import annotations\n'
                              'from dataclasses import dataclass\n'
                              'from .models import RouteDecision, TaskRecord\n'
                              '\n'
                              '\n'
                              '@dataclass(frozen=True)\n'
                              'class ModelProfile:\n'
                              '    name: str\n'
                              '    provider: str\n'
                              '    model: str\n'
                              '    runtime: str\n'
                              '    billing: str\n'
                              '    quality: int\n'
                              '    cost: int\n'
                              '    domains: tuple[str, ...]\n'
                              '\n'
                              '\n'
                              'PROFILES = (\n'
                              '    ModelProfile("local_daily", "local", "qwen3:8b", "hermes", "local", 2, 0, '
                              '("general",)),\n'
                              '    ModelProfile("cheap_daily", "deepseek", "deepseek-chat", "api", "api", 3, 1, '
                              '("general", "operations")),\n'
                              '    ModelProfile("qwen_batch", "qwen", "qwen-plus", "api", "api", 3, 1, ("general", '
                              '"operations")),\n'
                              '    ModelProfile("research_long", "moonshot", "kimi-k2.5", "api", "api", 4, 2, '
                              '("research",)),\n'
                              '    ModelProfile("trend_current", "xai", "grok", "api", "api", 4, 3, ("trends", '
                              '"research")),\n'
                              '    ModelProfile("claude_architecture", "anthropic", "claude", "claude-code", '
                              '"subscription", 5, 1, ("engineering",)),\n'
                              '    ModelProfile("codex_build", "openai", "codex", "codex", "subscription", 5, 1, '
                              '("engineering",)),\n'
                              '    ModelProfile("premium_general", "openai", "gpt", "api", "api", 5, 4, ("general", '
                              '"content")),\n'
                              ')\n'
                              '\n'
                              '\n'
                              'class ModelRouter:\n'
                              '    def __init__(self, strategy: str = "subscription_first"):\n'
                              '        self.strategy = strategy\n'
                              '\n'
                              '    def route(self, task: TaskRecord, purpose: str = "execute") -> RouteDecision:\n'
                              '        domain = task.domain or "general"\n'
                              '        if domain == "engineering":\n'
                              '            preferred = "claude_architecture" if purpose in {"plan", "review"} else '
                              '"codex_build"\n'
                              '        elif domain == "research":\n'
                              '            preferred = "research_long"\n'
                              '        elif domain == "trends":\n'
                              '            preferred = "trend_current"\n'
                              '        elif task.max_cost_usd <= 0:\n'
                              '            preferred = "local_daily"\n'
                              '        elif task.risk.value in {"high", "critical"}:\n'
                              '            preferred = "premium_general"\n'
                              '        else:\n'
                              '            preferred = "cheap_daily"\n'
                              '        profile = next(item for item in PROFILES if item.name == preferred)\n'
                              '        return RouteDecision(\n'
                              '            profile=profile.name, provider=profile.provider, model=profile.model,\n'
                              '            runtime=profile.runtime, billing=profile.billing,\n'
                              '            reason=f"domain={domain}; purpose={purpose}; strategy={self.strategy}",\n'
                              '            estimated_cost_usd=0.0 if profile.billing in {"local", "subscription"} else '
                              'min(task.max_cost_usd, 0.25),\n'
                              '        )\n',
 'src/cano_hermes/runtimes.py': 'from __future__ import annotations\n'
                                'import os\n'
                                'import subprocess\n'
                                'from dataclasses import dataclass\n'
                                'from pathlib import Path\n'
                                'from uuid import uuid4\n'
                                'from .models import ExecutionResult, TaskRecord\n'
                                '\n'
                                '\n'
                                '@dataclass(frozen=True)\n'
                                'class RuntimeRequest:\n'
                                '    task: TaskRecord\n'
                                '    prompt: str\n'
                                '    workspace: Path\n'
                                '    timeout_seconds: int = 900\n'
                                '\n'
                                '\n'
                                'class RuntimeExecutor:\n'
                                '    name = "base"\n'
                                '    def command(self, request: RuntimeRequest) -> list[str]:\n'
                                '        raise NotImplementedError\n'
                                '\n'
                                '    def execute(self, request: RuntimeRequest, dry_run: bool = True) -> '
                                'ExecutionResult:\n'
                                '        command = self.command(request)\n'
                                '        execution_id = f"exec-{uuid4().hex[:12]}"\n'
                                '        if dry_run:\n'
                                '            return ExecutionResult(execution_id=execution_id, '
                                'task_id=request.task.id,\n'
                                '                runtime=self.name, status="dry_run", command=command, dry_run=True)\n'
                                '        env = {key: value for key, value in os.environ.items() if key not in '
                                '{"PYTHONINSPECT"}}\n'
                                '        completed = subprocess.run(command, cwd=request.workspace, env=env, '
                                'text=True,\n'
                                '            capture_output=True, timeout=request.timeout_seconds, shell=False, '
                                'check=False)\n'
                                '        return ExecutionResult(execution_id=execution_id, task_id=request.task.id,\n'
                                '            runtime=self.name, status="completed" if completed.returncode == 0 else '
                                '"failed",\n'
                                '            command=command, stdout=completed.stdout[-20000:], '
                                'stderr=completed.stderr[-20000:],\n'
                                '            return_code=completed.returncode, dry_run=False)\n'
                                '\n'
                                '\n'
                                'class ClaudeCodeExecutor(RuntimeExecutor):\n'
                                '    name = "claude-code"\n'
                                '    def command(self, request: RuntimeRequest) -> list[str]:\n'
                                '        return ["claude", "-p", request.prompt, "--output-format", "stream-json",\n'
                                '                "--permission-mode", "plan", "--max-turns", "20"]\n'
                                '\n'
                                '\n'
                                'class CodexExecutor(RuntimeExecutor):\n'
                                '    name = "codex"\n'
                                '    def command(self, request: RuntimeRequest) -> list[str]:\n'
                                '        return ["codex", "exec", "--sandbox", "workspace-write", request.prompt]\n'
                                '\n'
                                '\n'
                                'class HermesExecutor(RuntimeExecutor):\n'
                                '    name = "hermes"\n'
                                '    def command(self, request: RuntimeRequest) -> list[str]:\n'
                                '        return ["hermes", "chat", "--prompt", request.prompt]\n'
                                '\n'
                                '\n'
                                'class OpenClawExecutor(RuntimeExecutor):\n'
                                '    name = "openclaw"\n'
                                '    def command(self, request: RuntimeRequest) -> list[str]:\n'
                                '        return ["openclaw", "run", "--prompt", request.prompt]\n'
                                '\n'
                                '\n'
                                'EXECUTORS = {item.name: item for item in (ClaudeCodeExecutor(), CodexExecutor(), '
                                'HermesExecutor(), OpenClawExecutor())}\n',
 'src/cano_hermes/static/app.js': 'async function json(url, options){const r=await fetch(url,options);if(!r.ok)throw '
                                  'new Error(await r.text());return r.json()}\n'
                                  'async function refresh(){const [health,tasks]=await '
                                  "Promise.all([json('/health'),json('/api/tasks')]);document.querySelector('#health').textContent=health.dry_run?'SAFE "
                                  '/ DRY '
                                  "RUN':'LIVE';document.querySelector('#agents').textContent=health.agents;document.querySelector('#skills').textContent=health.skills;document.querySelector('#tasks').textContent=tasks.length;document.querySelector('#task-list').innerHTML=tasks.map(t=>`<div "
                                  'class="task"><div><b>${t.title}</b><br><small>${t.domain} · '
                                  "${t.assigned_agent||'sin asignar'}</small></div><button "
                                  'onclick="runTask(\'${t.id}\')">${t.status}</button></div>`).join(\'\')||\'<small>No '
                                  "hay tareas.</small>'}\n"
                                  "async function runTask(id){await json(`/api/tasks/${id}/run`,{method:'POST'});await "
                                  'refresh()}\n'
                                  "document.querySelector('#task-form').addEventListener('submit',async "
                                  'e=>{e.preventDefault();await '
                                  "json('/api/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:title.value,objective:objective.value})});e.target.reset();await "
                                  'refresh()});refresh();\n',
 'src/cano_hermes/static/index.html': '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta '
                                      'name="viewport" content="width=device-width,initial-scale=1"><title>Cano Hermes '
                                      'OS</title><link rel="stylesheet" '
                                      'href="/static/style.css"></head><body><aside><h1>Hermes '
                                      'OS</h1><nav>Home<br>Tasks<br>Agents<br>Nexus<br>Forge<br>Costs<br>Approvals</nav></aside><main><header><div><small>COMMAND '
                                      'CENTER</small><h2>Autonomía supervisada</h2></div><span '
                                      'id="health">Conectando…</span></header><section class="cards"><article><b '
                                      'id="agents">0</b><span>Agentes</span></article><article><b '
                                      'id="skills">0</b><span>Skills</span></article><article><b '
                                      'id="tasks">0</b><span>Tareas</span></article><article><b>SAFE</b><span>Modo</span></article></section><section '
                                      'class="panel"><h3>Nueva tarea</h3><form id="task-form"><input id="title" '
                                      'placeholder="Título" required><textarea id="objective" placeholder="Qué debe '
                                      'entregar Hermes" '
                                      'required></textarea><button>Planear</button></form></section><section '
                                      'class="panel"><h3>Task Board</h3><div '
                                      'id="task-list"></div></section></main><script '
                                      'src="/static/app.js"></script></body></html>\n',
 'src/cano_hermes/static/style.css': ':root{font-family:Inter,system-ui;color:#e8eef8;background:#07111f}*{box-sizing:border-box}body{margin:0;display:grid;grid-template-columns:230px '
                                     '1fr;min-height:100vh}aside{padding:28px;background:#0b1728;border-right:1px '
                                     'solid #23324a}aside h1{margin:0 0 '
                                     '30px;color:#8bd5ff}nav{line-height:2.5;color:#98a9c3}main{padding:30px;max-width:1300px;width:100%}header{display:flex;justify-content:space-between;align-items:center}header '
                                     'small{color:#5eead4}header h2{margin:.3rem 0 '
                                     '1.5rem;font-size:2rem}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.cards '
                                     'article,.panel{background:#0d1b2e;border:1px solid '
                                     '#263750;border-radius:16px;padding:20px}.cards '
                                     'b{display:block;font-size:1.7rem}.cards '
                                     'span{color:#91a3be}.panel{margin-top:18px}form{display:grid;gap:12px}input,textarea,button{font:inherit;border-radius:10px;border:1px '
                                     'solid '
                                     '#334765;padding:12px;background:#081421;color:#eef}textarea{min-height:90px}button{background:#1677ff;border:0;font-weight:700;cursor:pointer}.task{display:grid;grid-template-columns:1fr '
                                     'auto;gap:8px;padding:12px 0;border-bottom:1px solid #263750}.task '
                                     'small{color:#91a3be}@media(max-width:800px){body{grid-template-columns:1fr}aside{display:none}.cards{grid-template-columns:repeat(2,1fr)}}\n'}
