FILES = {'src/cano_hermes/api.py': 'from __future__ import annotations\n'
                           'from pathlib import Path\n'
                           'from fastapi import FastAPI, HTTPException\n'
                           'from fastapi.responses import FileResponse\n'
                           'from fastapi.staticfiles import StaticFiles\n'
                           'from .config import get_settings\n'
                           'from .conductor import Conductor\n'
                           'from .forge import AgentForge\n'
                           'from .models import TaskCreate\n'
                           'from .nexus import Nexus\n'
                           'from .policy import PolicyEngine\n'
                           'from .registry import CapabilityRegistry\n'
                           'from .router import ModelRouter\n'
                           'from .store import SQLiteStore\n'
                           '\n'
                           '\n'
                           'def build_app(root: Path | None = None, db_path: str | Path | None = None) -> FastAPI:\n'
                           '    settings = get_settings(root)\n'
                           '    settings.data_dir.mkdir(parents=True, exist_ok=True)\n'
                           '    store = SQLiteStore(db_path or settings.data_dir / "hermes.db")\n'
                           '    registry = CapabilityRegistry(settings.agents_dir, settings.skills_dir)\n'
                           '    conductor = Conductor(store, registry, ModelRouter(settings.routing_strategy),\n'
                           '                          PolicyEngine(), settings.root, settings.dry_run)\n'
                           '    nexus = Nexus(settings.vault_dir)\n'
                           '    forge = AgentForge(settings.root / "generated")\n'
                           '    app = FastAPI(title="Cano Hermes Agentic OS", version="0.2.0")\n'
                           '    app.state.store, app.state.registry, app.state.conductor = store, registry, conductor\n'
                           '\n'
                           '    @app.get("/health")\n'
                           '    def health():\n'
                           '        return {"status": "ok", "version": "0.2.0", "dry_run": settings.dry_run,\n'
                           '                "agents": len(registry.agents()), "skills": len(registry.skills())}\n'
                           '\n'
                           '    @app.get("/api/tasks")\n'
                           '    def list_tasks():\n'
                           '        return store.list_tasks()\n'
                           '\n'
                           '    @app.post("/api/tasks")\n'
                           '    def create_task(data: TaskCreate):\n'
                           '        return conductor.plan(data)\n'
                           '\n'
                           '    @app.get("/api/tasks/{task_id}")\n'
                           '    def get_task(task_id: str):\n'
                           '        task = store.get_task(task_id)\n'
                           '        if task is None:\n'
                           '            raise HTTPException(404, "task not found")\n'
                           '        return {"task": task, "events": store.list_events(task_id)}\n'
                           '\n'
                           '    @app.post("/api/tasks/{task_id}/run")\n'
                           '    def run_task(task_id: str):\n'
                           '        try:\n'
                           '            return conductor.run(task_id)\n'
                           '        except KeyError as exc:\n'
                           '            raise HTTPException(404, "task not found") from exc\n'
                           '\n'
                           '    @app.get("/api/agents")\n'
                           '    def agents():\n'
                           '        return registry.agents()\n'
                           '\n'
                           '    @app.get("/api/skills")\n'
                           '    def skills():\n'
                           '        return registry.skills()\n'
                           '\n'
                           '    @app.get("/api/nexus/search")\n'
                           '    def search_nexus(q: str):\n'
                           '        return nexus.search(q)\n'
                           '\n'
                           '    @app.post("/api/forge/agents")\n'
                           '    def forge_agent(payload: dict):\n'
                           '        required = {"id", "team", "objective"}\n'
                           '        if not required <= payload.keys():\n'
                           '            raise HTTPException(422, "id, team and objective are required")\n'
                           '        path = forge.create_agent(payload["id"], payload["team"], payload["objective"])\n'
                           '        return {"status": "candidate", "path": str(path)}\n'
                           '\n'
                           '    static = Path(__file__).with_name("static")\n'
                           '    app.mount("/static", StaticFiles(directory=static), name="static")\n'
                           '\n'
                           '    @app.get("/", include_in_schema=False)\n'
                           '    def index():\n'
                           '        return FileResponse(static / "index.html")\n'
                           '\n'
                           '    return app\n'
                           '\n'
                           '\n'
                           'app = build_app()\n'}
